version: '3'

services:
  app:
    build: app
    restart: always
    env_file: .env
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: /usr/local/bin/gunicorn django_app.wsgi:application -w 2 -b :8000 --reload
    expose:
      - 8000

  nginx:
    build: nginx
    restart: always
    volumes:
      - ./app/static:/var/www/public/static
    ports:
      - 8080:80
    depends_on:
      - app

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    driver: bridge
