version: '3'

services:
  web:
    build: web
    restart: always
    container_name: django-web
    env_file: .env
    volumes:
      - ./web:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    command: /usr/local/bin/gunicorn django_app.wsgi:application -w 2 -b :8000

  nginx:
    build: nginx
    restart: always
    container_name: django-nginx
    volumes:
      - ./web/static:/var/www/public/static
    ports:
      - 8080:80
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    driver: bridge